import type { Metadata } from "next";
import Header from "../components/header";
import Link from "next/link";
import "../globals.css"



export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body

            >
                <Header />
                <div className="page-nav" style={{ width: "350px" }}>
                    <p>
                        <Link href={"/patients"}>
                            <span className="history">Patients</span>
                        </Link>
                        <span className="history" style={{
                            width: "auto",
                            position: "absolute",
                            left: "240px"
                        }}>/View Patient</span>
                        <span style={{
                            width: "auto",
                            position: "absolute",
                            left: "345px",
                            top: "107px",
                            fontSize: "24px"
                        }}>/Assign Package to Patient</span>
                    </p>


                </div>
                <div className="divider" style={{
                    position: "absolute",
                    top: "150px"
                }}></div>

                {children}
            </body>
        </html>
    );
}
